### ISSUE TITLE
Add singular kernel to Jupyter kernel wiki page

### ISSUE THREAD

**Issue by jasongrout** [sebasguts/jupyter_kernel_singular#3]
This is awesome - thanks for doing this. Would you add a row to the Jupyter Kernel wiki page so we can more widely advertise this?

https://github.com/jupyter/jupyter/wiki/Jupyter-kernels

Thanks!

**Comment by sebasguts** [comment]
Did that, thank you :)

**Comment by jasongrout** [comment]
Thanks!
